runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /fetch
  script: main.app
  secure: always

- url: /
  static_files: public/index.html
  upload: public/index.html
  secure: always

- url: /(.*)
  static_files: public/\1
  upload: public/(.*)

automatic_scaling:
  min_idle_instances: 1
